services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      DOCKER_API_VERSION: 1.46
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.24
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyterContainer
    ports:
      - "8888:8888"
      - "4040-4045:4040-4045"
    volumes:
      - ./notebooks:/home/jovyan/work

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test2021
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

networks:
  kafka-network:
    driver: bridge